### PR TITLE
Update Portuguese(Brazil)

### PR DESCRIPTION
**Pull request by azurejoga**
* updated several strings.
* translated new strings, including those with _ 
* Waiting for correction @zargonbr

### CODE REVIEW

**Comment by Apaczer** [comment]
Hi, thanks for fast response.

About strings with underscore sings, these are configuration options and you can read more in [README](https://github.com/MiyooCFW/gmenu2x?tab=readme-ov-file#special-strings-in-translation-file). Examples with filed options in other translations.

The [about](https://github.com/MiyooCFW/gmenu2x/blob/master/_about_.txt) in GMenu2X can also be translated, just create "_about_pt-br.txt" file in top-level directory from _about_.txt file.

**Comment by azurejoga** [comment]
@Apaczer create it for me and I will translate it.
 So _tts_voice_= wasn't supposed to be translated, right?

**Comment by Apaczer** [comment]
> @Apaczer create it for me and I will translate it.

done @azurejoga

> So tts_voice= wasn't supposed to be translated, right?

Right, those were not meant to be translated as is, you can leave that part.

**Comment by Apaczer** [comment]
@oliveruh could you help reviewing [Portuguese(Brazil)](https://github.com/MiyooCFW/gmenu2x/pull/82/files#diff-d31b059939ffdec8387a769f8a6e2e14acf5ce8f37fb4d3c61c3b28c81416ae5) and translating [_about_pt-br.txt](https://github.com/MiyooCFW/gmenu2x/blob/1dedf9b29d25300884efaad98ae0b6561ae5063e/_about_pt-br.txt)

**Comment by azurejoga** [comment]
Files translated successfully!
* contributors.md
* about_pt-BR.txt 
I hope everything is ok!

**Comment by Apaczer** [comment]
thanks! I will be just adding ALTernative kbd layout for pr(br) and we will be ready for merge.

**Comment by azurejoga** [comment]
😁❤️❤️, If you need me, I'll be here

**Pull request merged**
