### PR TITLE
add Text-To-Speech support with eSpeak

### PR DESCRIPTION
**Pull request by Apaczer**
Function allyTTS() from "a11y" acronym for accessibility. I'm suprised how well it works on such a device (outputing text-to-audio in real time).

Thanks guys for providing necessary info and code.

TODO:
- [x] optionize TTS for non-blind
- [x] read "buttons" and theirs usage (in msgbox)
- [x] read "inputDialog" for renaming things, adding text and parameters
- [x] read "Descriptions" only when asked for e.g. appLinks (now it's only the Title)
- [x] read integer/string values in options when selected (if asked maybe?)
- [x] read text output in TextDialog for e.g Logs, opening *.txt , *.zip files (another function for `espeak -f` cmd maybe?)
- [x] change voice when "language" setting is modified (`espeak -v` cmd)
- [x] read also "Section" first at startup and after switch

### CODE REVIEW

**Comment by zargonbr** [comment]
Thank you, Apaczer GH!  honestly, I don't even know how to thank you and the rest of the devs present on discord.  As for the test to speech issue on normal boot and first boot, this could be remedied with the following suggestions.  I don't know if they are possible, but I believe so since they don't require a lot of complex things.  The first suggestion is as follows.  1. the test to speech could be started at boot and on the first boot if the file containing the instructions to call it is present in the boot partition.  This prevents sighted people from throwing their consoles at the wall for fear of them talking to themselves.  .  The second suggestion is as follows.  The test to speech could be started if a specific button on the console is pressed and held after the physical button to turn on the console is used, and the boot begins.

**Comment by Apaczer** [comment]
@zargonbr,

I fixed major issue, when launching emulator/app while TTS is still playing in background (see https://github.com/MiyooCFW/gmenu2x/pull/34/commits/bd6fa722e9c8f7facca89f8ecfc934a8babca476). 
Please update you gmenu2x binary to this one: https://github.com/MiyooCFW/gmenu2x/suites/16758099171/artifacts/957088199

About your suggestion for firstboot procedure, I possibly would go with 1st idea (seems more safier) because to correctly configure inputs you need to perform part of this procedure e.g. `/boot/activate_accesability-OFF` empty file could do the trick.

**Comment by azurejoga** [comment]
hello friend!
I can't even thank you enough! you are doing a good job!
As a blind player and tester I am very happy!
and know that many people are loving the work you and the other developers are doing.

However, I have a question to ask.

Do you think it would be possible for me to virtualize the operating system to test accessibility?
What distro is miyoo based on and what operating system does it use?
I'll try to emulate to test accessibility and make more pull requests and issues to help find bugs and other things...
I will be very happy for your answer!

**Comment by Apaczer** [comment]
@azurejoga, I appreciate any engagment, be it testing or developing. I was not aware there is such demand for TTS in retro community (got my lesson).

MiyooCFW is based of buildroot not necessary any distro (some like to call it a Dingux system) with custom kernel and uboot to make HW stuff to work.

The easiest way to perform tests is to use PC build for Linux (see Makefile.linux) and get `espeak` app from e.g. `apt-get` on your machine. Here is sample output of gmenu2x-linux build from current PR: [gmenunx.linux.zip](https://github.com/MiyooCFW/gmenu2x/files/12786867/gmenunx.linux.zip)
(you probably need also sdl-1.2 installed to get it running). To change input bindings modify `input.conf` file.

There is still lot of stuff to do, read 1 comment.

**Comment by matrheine** [comment]
hey! just want to congratulate you for doing this awesome job of adding tts support to these fantastic devices! it'll be a dream come true to be able to know what's going on when using the device without having to guess where every game is located. i'll definitely buy a device to be able to enjoy and play my favorite retro games in an accessible way! you're awesome! do you have a list of handhelds that will work with this custom firmware? i'll probably get the most powerful device available. sorry for the dumb question.

**Comment by zargonbr** [comment]
@matrheine BittBoy v1, v2, v2.5, v3, v3.5
Pocket Go
PowKiddy Q90
PowKiddy V90
PowKiddy Q20 Mini
Sup M3 v1, v2
(See notes)
XYC Q8
Powkiddy X7
(Not confirmed)
Notes: Only devices with Allwinner F1C100S or F1C500S SOC are supported and even these can come with not fully compatible components (e.g. unfamiliar LCD display). There were reports of console revisions with "updated" SOC - F1E200.
The Not confirmed consoles are not supported yet, these consoles are under revision and may not be on the final compatibility list.
github.com/TriForceX/MiyooCFW/wiki

**Comment by azurejoga** [comment]
@Apaczer 

I'm just confused about one thing, is it possible to do this on Windows? and what would be the first steps towards that. I have basic experience with Linux so...

**Comment by zargonbr** [comment]
hello.  I don't know if anyone else testing besides me noticed anything.  when you enter the menu to select the language, it is as if you cannot enter.  It's as if the option wasn't clickable.  the espeak in that language menu has a problem.  I looked with a sighted person, and the options for selecting the language appear on the screen.  only espeak that you don't read.  and sometimes he speaks a part of the language but that's it and continues speaking the main menu options as we navigate with the d-pads.  As for the project’s performance, it’s wonderful!  I was honestly surprised by what this console is capable of doing together with great developers.  Apaczer, as for espeak, it is running in the background, and is killed when we enter an emulator or an app.  Would it be possible to make espeak activated as soon as the emulator menu is shown?  I'm referring to that emulator options menu where you have the options quit, save, load, etc., then when we select resume to return to the game it is killed.

**Comment by Apaczer** [comment]
@matrheine thanks, I would probably wait for this PR to be merged before using new code on the device itself. Lot of stuff need to be done before making it fully accessible (but we're on it, see above list!).  
You might get PocketGO which might support RUMBLE and give u additional functionality (like info about depleting battery or in-game sensations if they support such a feature), otherwise buy one from Powkiddy family.

@azurejoga, I'm also on Windows and for Linux's GUI Virtualization I prefer to use VirtualBox on my PC.

@zargonbr
We're lacking now many translations, you could all help and look for missing sentences in `assets/translations` directory (you can DM me or make a PR with changes).
About emulators supporting eSpeak, it would require enormous work to recompile every app with TTS code. Far easier solution would be reusing RetroArch code or even better porting Picoarch or [sdlretro](https://github.com/soarqin/sdlretro) with simpler menu navigation and support for libretro cores, however that's a story for another day :wink:.

**Comment by zargonbr** [comment]
Well, regarding the issue of emulators in v 90, I'll opt for retroarch.  This means less work having to recode the emulators;  having to recode the emulators is work and you are already doing a great job, a Herculean job to be honest with a device with very limited specifications.  Honestly, what the project is achieving in v90 is already making me very satisfied;  I don't even know how to thank you for your hard work.  The retroarch website says that in addition to the Windows version, the Linux version also has the accessibility option.  I just couldn't activate it in v 90. I tried changing the accessibility=true option in the settings file to see if it worked, but no feedback.  As for translating the files, fortunately gmmenu already has a translation for my language, which is Brazilian Portuguese.  But even so, I'll take a look to see if there's anything missing from being translated in the language file

**Comment by azurejoga** [comment]
@Apaczer  I thank everyone who is maintaining this incredible project!
Regarding emulators, you may have to do something additional.
But the best option is retroarch, which requires less work.

@zargonbr
  Maybe accessibility is only supported on ubuntu?

  For Ubuntu, you can install espeak by running “sudo apt-get install espeak” and then “sudo apt-get install espeak-data” for the additional voices.


Accessibility is activated in the same way as in Windows with its graphical interface.

also, i will definitely translate the missing parts of gmenu and other things.

**Comment by azurejoga** [comment]
I'm very happy to say that you contribute to this project, even if it's with translation!

And to this day, I enthusiastically follow the  pull requests

Could you say what has changed?
@Apaczer

**Comment by Apaczer** [comment]
Hi @azurejoga, we could merge it as is, but I wan't to do it right. Missing stuff:
- read "inputDialog" for renaming things, adding text and parameters
- read text output in TextDialog for e.g Logs, opening *.txt , *.zip files (`espeak -f` cmd)
- read "Sections" first after switch or at startup

So far I optimized a bit accesibility function, made it optional, made voice change available from translation text file, made settings fully readable with TTS.

**Comment by zargonbr** [comment]
Hi Apaczer.  I'm sorry for the inconvenience, but I would like to know.  Can you start the test to speech through the script at first boot in the new version?  As for the issue of translating, what is still missing?  me and azure can try to help

**Comment by Apaczer** [comment]
Hi @zargonbr, there were no changes to `firstboot` procedure - there are many issue with it which fludded after first official pre-release, so they have to be adressed foremost.

>  As for the issue of translating, what is still missing?

I don't follow, what specific issue? If you mean this PR, it's in the "workshop" but needs time 😅

**Comment by Apaczer** [comment]
will be closing in soon, for the future I plan to use [libespeak API](https://espeak.sourceforge.net/speak_lib.h) to optimize, instead of plain `system("espeak")` func calls.

**Pull request merged**
