### PR TITLE
Altered fonts for NeonWave theme and GameShow theme

### PR DESCRIPTION
**Pull request by MayanKoyote**
Altered glyphs: U+0401, U+0410-U+042F, U+0430-U+044F, U+0451, U+232B (Russian alphabet and "Erase to the Left").
Perhaps these glyphs could look better, but in any case it's better than nothing.
S01
S02

### CODE REVIEW

**Comment by Apaczer** [comment]
👍 when you're done, you should update version number in font metadata (easy todo from fontforge) and update changelog in font-modify.info file of corresponding skin like for e.g. in: https://github.com/MiyooCFW/gmenu2x/blob/master/assets/skins/FontiGrid/font-modify.info

**Comment by MayanKoyote** [comment]
I think I'm done with this for now. FontForge is killing me (and I have no desire to read the documentation for it).
The current task was simply to make the letters of the Russian alphabet.
Perhaps later someday I will finish special characters for the on-screen keyboard, but that will be quite later.
As for the font-modify.info files, I'll try to add them. Just don’t be surprised by the crazy version numbers.

**Comment by Apaczer** [comment]
Ok so these would be modified glyphs essentially (just using fontdiffenator):
<details>
 <summary> ps-glyph diff </summary>
 
glyph | diff | string
--- | --- | --- | 
uni232B | 0.805 | ⌫
uni0445 | 0.7093 | х
uni0443 | 0.7036 | у
uni0423 | 0.7036 | У
uni043C | 0.6746 | м
uni043A | 0.6745 | к
uni044E | 0.6741 | ю
uni044B | 0.6709 | ы
uni0437 | 0.6675 | з
uni044F | 0.6671 | я
uni0441 | 0.667 | с
uni0436 | 0.6638 | ж
uni043E | 0.6596 | о
uni044A | 0.6561 | ъ
uni044C | 0.6521 | ь
uni043B | 0.6516 | л
uni043D | 0.6405 | н
uni0424 | 0.6404 | Ф
uni043F | 0.6373 | п
uni0425 | 0.6366 | Х
uni0433 | 0.6343 | г
uni0448 | 0.6342 | ш
uni0435 | 0.634 | е
uni0417 | 0.6325 | З
uni0432 | 0.6322 | в
uni0434 | 0.627 | д
uni0430 | 0.6265 | а
uni0442 | 0.6209 | т
uni041C | 0.6204 | М
uni0447 | 0.617 | ч
uni0420 | 0.6155 | Р
uni0449 | 0.6111 | щ
uni0410 | 0.6103 | А
uni0451 | 0.6089 | ё
uni042F | 0.6065 | Я
uni042A | 0.6018 | Ъ
uni0411 | 0.6015 | Б
uni0415 | 0.6007 | Е
uni042B | 0.5994 | Ы
uni041A | 0.5979 | К
uni042C | 0.5972 | Ь
uni042E | 0.5959 | Ю
uni0438 | 0.5922 | и
uni041E | 0.5915 | О
uni0444 | 0.5908 | ф
uni0446 | 0.5892 | ц
uni0431 | 0.5861 | б
uni0439 | 0.5846 | й
uni0421 | 0.5838 | С
uni0416 | 0.5797 | Ж
uni0401 | 0.5788 | Ё
uni0413 | 0.5781 | Г
uni041B | 0.5741 | Л
uni0412 | 0.5734 | В
uni041D | 0.5686 | Н
uni0422 | 0.5667 | Т
uni041F | 0.5647 | П
uni044D | 0.5628 | э
uni0440 | 0.5606 | р
uni0428 | 0.5558 | Ш
uni0427 | 0.5494 | Ч
uni0414 | 0.5375 | Д
uni0429 | 0.5358 | Щ
uni0419 | 0.5252 | Й
uni0418 | 0.5242 | И
uni0426 | 0.5177 | Ц
uni042D | 0.5142 | Э

</details>

Could you also update `sfnt Revision` to "1.00402" showing second iteration of particular font. That is change PS and TTF Names in `Font Info`.

In MergedAudiowUNI.ttf please keep all new glyphs upper-case to go well with overall theme, this is specified in `font-modify.info`.

The diffenator warns about marks update in MergedKdaTPrUNI.ttf for over 200 glyphs, but my guess is that can't be simply overcome when generating fonts from GUI fontforge with only ttf files at hand.

**Comment by Apaczer** [comment]
Scrap comment about MergedAudiowUNI.ttf, not sure where I got that impression.

**Comment by MayanKoyote** [comment]
Yes, 67 glyphs total: 33x2 for letters and 1 for "Erase to the Left".
I can't change the `sfnt Revision`, after editing this field and closing the window it resets to the original value (1.00401). Although maybe I'm just doing it in a way it's not supposed to be done.
I'll recheck MergedKdaTPrUNI.ttf. There should also only be 67 modified glyphs.

**Comment by MayanKoyote** [comment]
I recreated the font files.
Now only 67 glyphs in each font should be marked as altered, since I definitely didn’t touch the others this time.

**Comment by Apaczer** [comment]
Afterall in "MergedKdaTPrUNI" when running `Element->Validation->Validate` you can discover major TrueType error with marks, that is "At least one anchor point was lost when pasting from one font to another because no matching anchor class could be found in the new font". Thus I had to remove unncessary anchor points in a few glyphs. Moreover auto-fixed generic (minor) problems in two fonts for "Missing extrema - the selected spline attains its extreme smw other than its endpoints", which makes prv and current fonts inline in that regard. 
For explanation I was getting segfault while copying glyphs, so [took my time](https://github.com/MiyooCFW/gmenu2x/commit/9c1526932dc287f405003f4611c976e051adc802#diff-2d7dc9ae23c67043071b8b367ea83c6b4981b9787e947eaab8f5d7f20bb8c55c) 😮‍💨 to debug this stuff, also we have an easy tool to copy&check new glyphs for merging.

For metadata modification I've used `ttx` from "[fonttools](https://github.com/fonttools/fonttools)" package, for least possibly issues when re-generating(building) fonts.

**Pull request merged**
