### PR TITLE
update Russian translation

### PR DESCRIPTION
**Pull request by MayanKoyote**
Making changes related to commit 4da6cd9.
* it seems the new mechanism doesn't like it when the line with keys ends with an 'equals' sign

### CODE REVIEW

**Comment by Apaczer** [comment]
ah yes, forgot that  the GMenu2X is looking in translation file for "=LF" or "=CRLF" sign and treat those lines as empty translations. I could move `=` sign in kbd somewhere else, but ppl are usually acustomed to that placement under QWERTY.

BTW: I changed a bit code, to use "Alt" for switching to custom lang keyboard.

**Comment by Apaczer** [comment]
tks, I borrowed your idea to make keyboard linear across switching! Pls consider upgrading your "Backspace" & "Space" translation again, maybe reusing ← or ⎵. I wouldn't recommend to use ⌫ (it is hardly readable on small resolution).

**Comment by MayanKoyote** [comment]
> I wouldn't recommend to use ⌫ (it is hardly readable on small resolution).

In general, I thought about redrawing this sign “by hands”. To make it big fat and nice.
Anyway, lately I’ve been finishing up the symbols for those fonts with missing Cyrillic that are used in current themes.
Although this process is boring and therefore long.

**Comment by Apaczer** [comment]
That's indeed a hell lot of work! If you'll feel there's to much to redraw, we could look for a complementary font with only e.g. Cyrilic signs going well with main skin font, and then merge them in.

**Comment by MayanKoyote** [comment]
Something like this: 'backspace' and 'space' are redrawn:

backspace-and-space-150

backspace-and-space-110

**Comment by Apaczer** [comment]
This may be an issue afterall for TTS engine for reading out-loud buttons and their description, but merging for now.

**Comment by Apaczer** [comment]
It is also a good practive to make all tables (keyboards layouts) linear across switching thus having the same number of characters - it is much easier to navigate that way.

**Pull request merged**
